### ISSUE TITLE
Brillo y Desaturación en qcolorcorrection

### ISSUE THREAD

**Issue by MarioMey** [pantaliQa/pantaliQa-core#1]
Abriendo el primer issue, esto lo hablamos en Matienzo.
- Agregar un "brightness" para llevarlo de full negro a full blanco.
- Modificar "saturation" para llevarlo al blanco/negro.

**Comment by husk00** [comment]
Hi Mario
gracias para esta rquest.
Mira el ultimo commit, he añadido la propiedad brightness al objeto qcolorcorrection

**Comment by MarioMey** [comment]
"Chusmeando" un poco, me fijé en el commit... y vi que cambiaste varios archivos. Según el título del commit, deberían haberse cambiado qcolorcorrection.pd y, a lo sumo, OVERVIEW.pd.

Por ejemplo, agregaste [alpha 1] a qcam.pd.

Nunca trabajé con GIT, pero me parece que el título del commit debería decir ni más ni menos que lo que se modificó. De última, comentar en el commit que se hicieron más cosas.

Lástima que usar el "diferenciador" de versiones/archivos no está hecho para archivos pd. No es fácil visualizar un patch viendo un archivo pd por dentro.

**Comment by husk00** [comment]
SIp, he ido cambiando varias cosas en ese commit, no solo el qcolorcorrection. Trataré de ser mas ordenado la próxima. Hay un cambio importante que todavía no he comunicado porqué no estoy seguro de dejarlo así. Por esto lo del alpha en qcam y en las demás source.
