### ISSUE TITLE
Agregar un loopback para procesar la imagen final.

### ISSUE THREAD

**Issue by MarioMey** [pantaliQa/pantaliQa-core#2]
Usar v4l2loopback para crear una nueva entrada de video para procesarla.

Sería importante que la salida final sea ésta y no la que va al loopback.

**Comment by husk00** [comment]
No entiendo bien lo que quieres lograr?
me explicas mejor?
Que es lo que piensas necesitar/hacer?

**Comment by MarioMey** [comment]
Uh... puede que me esté confundiendo. Algo hablamos del loopback... y, no se por qué, hoy pensé que habíamos pensado en algo así:

![loopback-boceto](https://cloud.githubusercontent.com/assets/4954109/9856632/4ce3066e-5aec-11e5-8f23-96e337366f37.png)

Si no estaba pensado esto... bueh, cerremos este issue.

**Comment by husk00** [comment]
Hay que ver si el modelo que propones, que tiene su lógica, va  a ser eficiente como performance en Gem. de momento funciona así:
![4ce3066e-5aec-11e5-8f23-96e337366f37](https://cloud.githubusercontent.com/assets/1175794/9857253/e3bf5ec2-5aef-11e5-9099-60414c77556a.png)

**Comment by MarioMey** [comment]
Bueno, en realidad no pensaba en que siempre estuviese activado el loopback. Que esto sería sólo si se quiere procesar la salida final.

Igualmente, en algún foro / IRC / loquesea me dijeron que había una forma de tomar lo que finalmente se vería en la ventana de GEM y usarlo. Tengo que ver quién me lo dijo... y de que manera. Con algún PIX_*.

Ahora me fijo si lo encuentro...

**Comment by MarioMey** [comment]
Había preguntado en la lista de Pd y IOhannes me contestó:

> |- How the patch should be if I want to send the GEM window to loopback?
> |I mean, not only the color and vertical inverted video, but the whole
> |window...
> 
> checkout [pix_snap] to fetch a framebuffer into pixes.

Me alegraría que esto fuese de ayuda. Saludos.

**Comment by husk00** [comment]
esto se logra con un gembuffer. Tienes una abstraction en list/abs que es copiada desde el proyect Extended ToolKit para usar el bufferde gem. El gran limite es que el buffer para funcionar tiene que estar al principio de cada cadena de rendering.

**Comment by husk00** [comment]
FIjate que el objecto v4loopback en list(abs ya utiliza el pix_snap. El punto que este metodo no es muy bueno a nivel de performance.

**Comment by MarioMey** [comment]
Bueno, ahora no puedo ponerme a probar... me pongo en modo suspensión...

¡Saludos!
